
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knnkkrbxjzdqapsfxmgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtubmtrcmJ4anpkcWFwc2Z4bWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNzAzMzAsImV4cCI6MjA1OTk0NjMzMH0.zzvL3HRy5uc6crRv0RFSZW93hfqTLb9ZTTBp1RFI3m4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
